# Generated by Django 3.2.15 on 2022-10-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imge',
            field=models.ImageField(default='abc', upload_to='image'),
            preserve_default=False,
        ),
    ]
